### PR TITLE
bumped versions

### PR DESCRIPTION
**Pull request by Poweranimal**

### CODE REVIEW

**Comment by sethvargo** [comment]
Is this to fix a bug or?

**Comment by Poweranimal** [comment]
My bad.
I thought it needs to be recompiled for the latest vault version `1.8.5`, but messed something up on my side.
That said, it doesn't fix a bug or anything else, it only bumps minor versions :smile:
I can close it, if needed.

**Comment by sethvargo** [comment]
I was going to wait until 1.9 comes out (I've been told "soon") and then do a bump because there's some small API changes in that version.

**Comment by Poweranimal** [comment]
Ok, no problem.
Closing this pr :smile:

**Pull request closed without merging**
